spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    url: jdbc:postgresql://localhost:5432/receipt
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  entitymanager:
    packages.to.scan: by.receipt.model
db:
  hibernate:
    hbm2ddl.auto: validate
    show_sql: 'true'
    connection.pool_size: '5'
app:
  percentDiscount: '0.9'
  filePath: check.txt
